{
 "title": "LivePerson Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Random Float Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(float_counter_total[10s])" }
   ]
  },
  {
   "title": "Random Fload Guage",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "float_guage" }
   ]
  },
  {
   "title": "Random Int Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(int_counter_total[10s])" }
   ]
  },
  {
   "title": "Random Int Guage",
   "type": "singlestat",
   "description": "0-1000",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "int_guage" }
   ]
  }
 ]
}